# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatApp
  pod 'Firebase/Core'
  target 'ChatApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  end

  target 'ChatAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ChatApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatApp-tvOS

  # target 'ChatApp-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
